### ISSUE TITLE
Conflicts with clojure.core/update in Clojure v1.7.0

### ISSUE THREAD

**Issue by nblumoe** [amalloy/useful#36]
clojure.core now comes with an `update` function itself: https://github.com/clojure/clojure/blob/master/changes.md#25-update---like-update-in-for-first-level

This gets replaced by `useful.map/update` now. Probably the function in `useful.map` can be removed.

**Comment by amalloy** [comment]
It could be removed for people using 1.7, but there's no particular need to, and it would impact users of earlier versions. The `refer-clojure :exclude update` is already in `useful.map`, meaning it doesn't produce warnings when compiled in clojure 1.7, so the only thing removing it would do is prevent errors for people who `:use` all of `useful.map` unqualified. That's not exactly a best practice, and I don't really mind if those folks are reminded it's not recommended.

**Comment by nblumoe** [comment]
Thanks. Yes, it means perfect sense as you explained. The issue for me was an outdated upstream dependency on `useful 0.8.6` via https://github.com/nilswloka/lein-cucumber
